version: '3'
services:
  client:
    build:
      context: '.'
      dockerfile: './Dockerfile.dev'
    ports:
      - '8080:8080'
    stdin_open: true
    volumes:
      - .:/usr/src/app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
